package com.data.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.data.entity.User;
import com.data.entity.Zhou;

import com.data.entity.UserDao;
import com.data.entity.ZhouDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig zhouDaoConfig;

    private final UserDao userDao;
    private final ZhouDao zhouDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        zhouDaoConfig = daoConfigMap.get(ZhouDao.class).clone();
        zhouDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        zhouDao = new ZhouDao(zhouDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Zhou.class, zhouDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        zhouDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ZhouDao getZhouDao() {
        return zhouDao;
    }

}
